title: Tomasz Kacprzak
theme: jekyll-theme-minimal
logo: /assets/img/logo.png
markdown: kramdown
show_downloads: True

github:
  is_user_page: False
  google_scholar_url: https://scholar.google.com/citations?user=1eZr_L0AAAAJ&hl=en&oi=ao
  cv_url: http://tomaszkacprzak.github.io/assets/CV_Tomasz_Kacprzak_230801.pdf
